# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smo_smm <- function(K, init_sd, W, init_a, y, C, dim_x, dim_y, epsilon, maxit) {
    .Call(`_ksmm_smo_smm`, K, init_sd, W, init_a, y, C, dim_x, dim_y, epsilon, maxit)
}

